export const citiesList = [
  "SGM",
  "STR",
  "A.Thirumuruganpoondi",
  "A.Vellalapatti",
  "Aadityana",
  "Aambaliyasan",
  "Aantaliya",
  "Aarambhada",
  "Abhayapuri",
  "Abiramam",
  "Abohar",
  "Abrama",
  "Abu Road",
  "Achabal",
  "Achalpur",
  "Achampudur",
  "Acharapakkam",
  "Acharipallam",
  "Achhalda",
  "Achhnera",
  "Achipatti",
  "Adalaj",
  "Adampur",
  "Adari",
  "Adikaratti",
  "Adilabad",
  "Adiramapattinam",
  "Adityapatna",
  "Adityapur",
  "Adoni",
  "Adoor",
  "Adra",
  "Aduthurai alias Maruthuvakudi",
  "Adyar",
  "Afzalgarh",
  "Afzalpur",
  "Agar",
  "Agaram",
  "Agartala",
  "Agarwal Mandi",
  "Agastheeswaram",
  "Agra",
  "Agra",
  "Ahiwara",
  "Ahmadnagar",
  "Ahmadnagar",
  "Ahmadpur",
  "Ahmadpur",
  "Ahmedabad",
  "Ahmedabad Cantonment",
  "Ahmedgarh",
  "Ahraura",
  "Aiho",
  "Ailum",
  "Air Force Area",
  "Aistala",
  "Aizawl",
  "Ajaigarh",
  "Ajhuwa",
  "Ajmer",
  "Ajnala",
  "Ajra",
  "Akalgarh",
  "Akaltara",
  "Akathiyoor",
  "Akbarpur",
  "Akbarpur",
  "Akhnoor",
  "Akkalkot",
  "Akkarampalle",
  "Akkayapalle",
  "Aklera",
  "Akoda",
  "Akodia",
  "Akola",
  "Akot",
  "Alagappapuram",
  "Alampalayam",
  "Alampur",
  "Aland",
  "Alandi",
  "Alandur",
  "Alang",
  "Alanganallur",
  "Alangayam",
  "Alangudi",
  "Alangulam",
  "Alangulam",
  "Alanthurai",
  "Alapakkam",
  "Alappuzha",
  "Alawalpur",
  "Aldona",
  "Ali Pur",
  "Alibag",
  "Aliganj",
  "Aligarh",
  "Alipurduar",
  "Alipurduar Rly.Jnc.",
  "Alirajpur",
  "Allahabad",
  "Allahabad",
  "Allahganj",
  "Allapur",
  "Allapuram",
  "Almora",
  "Almora",
  "Alnavar",
  "Along",
  "Alot",
  "Alpur",
  "Alur",
  "Alur",
  "Aluva",
  "Alwal",
  "Alwar",
  "Alwarkurichi",
  "Alwarthirunagiri",
  "Amadalavalasa",
  "Amalapuram",
  "Amalner",
  "Amanganj",
  "Amanpur",
  "Amarkantak",
  "Amarpatan",
  "Amarpur",
  "Amarpur",
  "Amarwara",
  "Ambad",
  "Ambada",
  "Ambagarh Chowki",
  "Ambah",
  "Ambaji",
  "Ambala",
  "Ambala Cantt.",
  "Ambala Sadar",
  "Ambarnath",
  "Ambasamudram",
  "Ambassa",
  "Ambattur",
  "Ambehta",
  "Ambejogai",
  "Ambikanagara",
  "Ambikapur",
  "Ambikapur Part-X",
  "Ambivali Tarf Wankhal",
  "Ambur",
  "Amet",
  "Amethi",
  "Amethi",
  "Amguri",
  "Amila",
  "Amilo",
  "Aminagar Sarai",
  "Aminagar Urf Bhurbaral",
  "Amini",
  "Amkula",
  "Amla",
  "Amlabad",
  "Amlai",
  "Amli",
  "Amloh",
  "Ammainaickanur",
  "Ammapettai",
  "Ammapettai",
  "Ammavarikuppam",
  "Ammoor",
  "Amodghata",
  "Amraudha",
  "Amravati",
  "Amreli",
  "Amritsar",
  "Amritsar Cantt.",
  "Amroha",
  "Amtala",
  "Anaimalai",
  "Anaiyur",
  "Anaiyur",
  "Anakapalle",
  "Anakaputhur",
  "Anand",
  "Anand Nagar",
  "Anandapur",
  "Anandnagar",
  "Anandpur Sahib",
  "Anantapur",
  "Ananthapuram",
  "Anantnag",
  "Ancharakandy",
  "Andada",
  "Andipalayam",
  "Andipatti Jakkampatti",
  "Andro",
  "Andul",
  "Anekal",
  "Angamaly",
  "Angarpathar",
  "Anjad",
  "Anjangaon",
  "Anjar",
  "Anjugramam",
  "Anklav",
  "Anklesvar",
  "Anklesvar INA",
  "Ankola",
  "Anksa",
  "Ankurhati",
  "Annamalai Nagar",
  "Annavasal",
  "Annigeri",
  "Annur",
  "Anpara",
  "Antah",
  "Antari",
  "Anthiyur",
  "Antu",
  "Anugul",
  "Anup Nagar",
  "Anupgarh",
  "Anuppur",
  "Anupshahr",
  "Aonla",
  "Appakudal",
  "Aquem",
  "Ara",
  "Arachalur",
  "Arakandanallur",
  "Arakonam",
  "Aralvaimozhi",
  "Arambag",
  "Arang",
  "Arani",
  "Arani",
  "Aranthangi",
  "Araria",
  "Arasiramani",
  "Aravakurichi",
  "Aravankad",
  "Arcot",
  "Areraj",
  "Argari",
  "Arimalam",
  "Ariyalur",
  "Ariyappampalayam",
  "Ariyur",
  "Arkalgud",
  "Arki",
  "Armapur Estate",
  "Arnia",
  "Aron",
  "Arookutty",
  "Aroor",
  "Arra",
  "Arrah",
  "Arsikere",
  "Arumanai",
  "Arumbavur",
  "Arumuganeri",
  "Aruppukkottai",
  "Arvi",
  "Asan Khurd",
  "Asansol",
  "Asarganj",
  "Ashok Nagar",
  "Ashokapuram",
  "Ashoknagar Kalyangarh",
  "Ashrafpur Kichhauchha",
  "Ashta",
  "Ashta",
  "Asifabad",
  "Asika",
  "Asind",
  "Asola",
  "Assandh",
  "Atarra",
  "Atasu",
  "Ateli",
  "Athagad",
  "Athani",
  "Athanur",
  "Athimarapatti",
  "Athipattu",
  "Athmallik",
  "Athni",
  "Athur",
  "Athur",
  "Atrauli",
  "Atraulia",
  "Attayampatti",
  "Attingal",
  "Attur",
  "Atul",
  "Aurad",
  "Auraiya",
  "Aurangabad",
  "Aurangabad",
  "Aurangabad",
  "Aurangabad",
  "Aurangabad",
  "Aurangabad Bangar",
  "Auras",
  "Ausa",
  "Avadattur",
  "Avadi",
  "Avalpoondurai",
  "Avanashi",
  "Avaniapuram",
  "Avinissery",
  "Awagarh",
  "Awantipora",
  "Ayakudi",
  "Aygudi",
  "Ayodhya",
  "Ayothiapattinam",
  "Ayyalur",
  "Ayyampalayam",
  "Ayyampettai",
  "Ayyampettai",
  "Azamgarh",
  "Azhagiapandiapuram",
  "Azhikode North",
  "Azhikode South",
  "Azizpur",
  "Azmatgarh",
  "B. Mallapuram",
  "B. Meenakshipuram",
  "Babai",
  "Babar Pur",
  "Babarpur Ajitmal",
  "Baberu",
  "Babhulgaon",
  "Babina",
  "Babiyal",
  "Bablari Dewanganj",
  "Babrala",
  "Babua Kalan",
  "Babugarh",
  "Bachhraon",
  "Bachhrawan",
  "Bad",
  "Bada Malhera",
  "Badagaon",
  "Badagoan",
  "Badami",
  "Badami Bagh",
  "Badarpur",
  "Badarpur Rly Town",
  "Badarwas",
  "Badawada",
  "Baddi",
  "Bade Bacheli",
  "Badepalle",
  "Badgam",
  "Badhagachhi",
  "Badharghat",
  "Badhni Kalan",
  "Badi",
  "Badkuhi",
  "Badlapur",
  "Badnagar",
  "Badnawar",
  "Badod",
  "Badoda",
  "Badra",
  "Badrinathpuri",
  "Baduria",
  "Bagaha",
  "Bagalkot",
  "Bagasara",
  "Bagbahara",
  "Bagbera",
  "Bagepalli",
  "Bageshwar",
  "Baggar",
  "Bagh",
  "Bagha Purana",
  "Baghmara",
  "Baghpat",
  "Bagli",
  "Bagnan",
  "Bagru",
  "Bah",
  "Bahadurganj",
  "Bahadurganj",
  "Bahadurgarh",
  "Baharampur",
  "Bahbari Gaon",
  "Baheri",
  "Bahirgram",
  "Bahjoi",
  "Bahraich",
  "Bahsuma",
  "Bahula",
  "Bahuwa",
  "Baidyabati",
  "Baihar",
  "Baikunthpur",
  "Baikunthpur",
  "Bail Hongal",
  "Bairabi",
  "Bairatisal",
  "Bairgania",
  "Bajala",
  "Bajna",
  "Bajpe",
  "Bajpur",
  "Bajva",
  "Bakani",
  "Bakewar",
  "Bakhtiarpur",
  "Bakiabad",
  "Bakloh",
  "Balachaur",
  "Balaghat",
  "Balagoda (Bolani)",
  "Balakrishnampatti",
  "Balakrishnapuram",
  "Balangir",
  "Balapallam",
  "Balapur",
  "Balaram Pota",
  "Balarampur",
  "Balarampur",
  "Balasamudram",
  "Balasinor",
  "Baldeo",
  "Baldeogarh",
  "Baleshwar",
  "Bali",
  "Baliari",
  "Balichak",
  "Balimela",
  "Balkundra",
  "Ballarpur",
  "Ballavpur",
  "Ballia",
  "Bally",
  "Bally",
  "Balod",
  "Baloda",
  "Baloda Bazar",
  "Balotra",
  "Balrampur",
  "Balugaon",
  "Balurghat",
  "Bambolim",
  "Bamhani",
  "Bamor",
  "Bamora",
  "Bamun Sualkuchi",
  "Bamunari",
  "Banapur",
  "Banarhat Tea Garden",
  "Banarsi",
  "Banat",
  "Banaur",
  "Banbasa",
  "Banda",
  "Banda",
  "Bandarulanka",
  "Bandhgora",
  "Bandia",
  "Bandikui",
  "Bandipore",
  "Bandora",
  "Banga",
  "Bangalore",
  "Bangaon",
  "Bangarapet",
  "Bangarmau",
  "Bangawan",
  "Bangramanjeshwar",
  "Bangura",
  "Banihal",
  "Banjar",
  "Banka",
  "Bankapura",
  "Banki",
  "Banki",
  "Bankner",
  "Bankra",
  "Bankura",
  "Banmankhi Bazar",
  "Bannur",
  "Bansatar Kheda",
  "Bansberia",
  "Bansdih",
  "Bansgaon",
  "Banshra",
  "Bansi",
  "Banswara",
  "Bantwa",
  "Bantwal",
  "Banupur",
  "Bapatla",
  "Bara Bamonia",
  "Barabazar",
  "Baragaon",
  "Baragaon",
  "Barahiya",
  "Baraily",
  "Barajamda",
  "Baramati",
  "Baramula",
  "Baran",
  "Baranagar",
  "Barapali",
  "Barasat",
  "Barauli",
  "Barauni IOC Township",
  "Baraut",
  "Barbari (AMC Area)",
  "Barbigha",
  "Barbil",
  "Barddhaman",
  "Bardoli",
  "Bareilly",
  "Bareilly",
  "Barela",
  "Baretta",
  "Bargarh",
  "Barghat",
  "Bargur",
  "Barh",
  "Barhalganj",
  "Barhani Bazar",
  "Barhi",
  "Barhi",
  "Bari",
  "Bari Brahmana",
  "Bari Sadri",
  "Barigarh",
  "Barijhati",
  "Baripada",
  "Bariwala",
  "Barjora",
  "Barkakana",
  "Barkhera",
  "Barkot",
  "Barmer",
  "Barnala",
  "Barpathar",
  "Barpeta",
  "Barpeta Road",
  "Barrackpur",
  "Barrackpur Cantonment",
  "Barsana",
  "Barshi",
  "Barua Sagar",
  "Barughutu",
  "Baruihuda",
  "Baruipur",
  "Barwadih",
  "Barwaha",
  "Barwala",
  "Barwani",
  "Barwar",
  "Basar",
  "Basaria",
  "Basavakalyan",
  "Basavana Bagevadi",
  "Bashohli",
  "Basirhat",
  "Baska",
  "Basmath",
  "Basna",
  "Basni Belima",
  "Basoda",
  "Bassi Pathana",
  "Basti",
  "Basudebpur",
  "Basugaon",
  "Basukinath",
  "Batala",
  "Bathinda",
  "Batlagundu",
  "Batote",
];
